name: CI - Build and Test (BooknFix)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd app-frontend
          npm install

      - name: Frontend Tests (app-frontend)
        run: |
          cd app-frontend
          npm run test

    