name: CI - Build and Test (BooknFix)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'app-frontend/package-lock.json'

      - name: Install dependencies
        run: |
          cd app-frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd app-frontend
          npm run test

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test microservice (auth-svc)
        run: |
          cd services/auth-svc
          mvn clean verify
