# name: Deploy React App to OCI Ubuntu

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.7.0
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy to OCI via SSH with Docker login
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
#             echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#             docker pull clau2005/app-booknfix:latest
#             docker stop app-booknfix || true
#             docker rm app-booknfix || true
#             docker run -d \
#               --name app-booknfix \
#               -p 80:80 \
#               clau2005/app-booknfix:latest
#           EOF
#       - name: Notify Deployment Success
#         run: echo "Deployment to OCI Ubuntu server successful!"